/**
*This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
*Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
*/

package
{
	import flash.display.Sprite;
	
	import flexUnitTests.TD_NewTests;
	
	public class FlexUnitCompilerApplication extends Sprite
	{
		
		private var flexUnitTests_TD_NewTests_obj:flexUnitTests.TD_NewTests;
	}
}